// ajax/libs/jqwidgets/12.0.4/jqwidgets-ts/angular_jqxtagcloud.ts
/*
jQWidgets v12.0.4 (2021-Apr)
Copyright (c) 2011-2021 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

/// <reference path="jqwidgets.d.ts" />

import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxdata.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxtagcloud.js';

import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
declare let JQXLite: any;

@Component({
    selector: 'jqxTagCloud',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxTagCloudComponent implements OnChanges
{
   @Input('alterTextCase') attrAlterTextCase: string;
   @Input('disabled') attrDisabled: boolean;
   @Input('displayLimit') attrDisplayLimit: number;
   @Input('displayMember') attrDisplayMember: string;
   @Input('displayValue') attrDisplayValue: boolean;
   @Input('fontSizeUnit') attrFontSizeUnit: string;
   @Input('maxColor') attrMaxColor: string;
   @Input('maxFontSize') attrMaxFontSize: number;
   @Input('maxValueToDisplay') attrMaxValueToDisplay: number;
   @Input('minColor') attrMinColor: string;
   @Input('minFontSize') attrMinFontSize: number;
   @Input('minValueToDisplay') attrMinValueToDisplay: number;
   @Input('rtl') attrRtl: boolean;
   @Input('sortBy') attrSortBy: string;
   @Input('sortOrder') attrSortOrder: string;
   @Input('source') attrSource: jqwidgets.TagCloudSource;
   @Input('tagRenderer') attrTagRenderer: (itemData: jqwidgets.TagCloudTagRenderer['itemData'], minValue: jqwidgets.TagCloudTagRenderer['minValue'], valueRange: jqwidgets.TagCloudTagRenderer['valueRange']) => any;
   @Input('takeTopWeightedItems') attrTakeTopWeightedItems: boolean;
   @Input('textColor') attrTextColor: string;
   @Input('urlBase') attrUrlBase: string;
   @Input('urlMember') attrUrlMember: string;
   @Input('valueMember') attrValueMember: string;
   @Input('width') attrWidth: string | number;
   @Input('height') attrHeight: string | number;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['alterTextCase','disabled','displayLimit','displayMember','displayValue','fontSizeUnit','height','maxColor','maxFontSize','maxValueToDisplay','minColor','minFontSize','minValueToDisplay','rtl','sortBy','sortOrder','source','tagRenderer','takeTopWeightedItems','textColor','urlBase','urlMember','valueMember','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxTagCloud;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean = false;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxTagCloud(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxTagCloud(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxTagCloud(this.properties[i])) {
                  this.host.jqxTagCloud(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
         return false;
      }
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      if (classes.length > 0) {
        childEl.classList.add(...classes);
      }
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (this.host) {
         return;
      }
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxTagCloud', options);

   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      if(this.host) this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxTagCloud('setOptions', options);
   }

   // jqxTagCloudComponent properties
   alterTextCase(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('alterTextCase', arg);
      } else {
          return this.host.jqxTagCloud('alterTextCase');
      }
   }

   disabled(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxTagCloud('disabled', arg);
      } else {
          return this.host.jqxTagCloud('disabled');
      }
   }

   displayLimit(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayLimit', arg);
      } else {
          return this.host.jqxTagCloud('displayLimit');
      }
   }

   displayMember(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayMember', arg);
      } else {
          return this.host.jqxTagCloud('displayMember');
      }
   }

   displayValue(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayValue', arg);
      } else {
          return this.host.jqxTagCloud('displayValue');
      }
   }

   fontSizeUnit(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('fontSizeUnit', arg);
      } else {
          return this.host.jqxTagCloud('fontSizeUnit');
      }
   }

   height(arg?: number | string): number | string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('height', arg);
      } else {
          return this.host.jqxTagCloud('height');
      }
   }

   maxColor(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxColor', arg);
      } else {
          return this.host.jqxTagCloud('maxColor');
      }
   }

   maxFontSize(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxFontSize', arg);
      } else {
          return this.host.jqxTagCloud('maxFontSize');
      }
   }

   maxValueToDisplay(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxValueToDisplay', arg);
      } else {
          return this.host.jqxTagCloud('maxValueToDisplay');
      }
   }

   minColor(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minColor', arg);
      } else {
          return this.host.jqxTagCloud('minColor');
      }
   }

   minFontSize(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minFontSize', arg);
      } else {
          return this.host.jqxTagCloud('minFontSize');
      }
   }

   minValueToDisplay(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minValueToDisplay', arg);
      } else {
          return this.host.jqxTagCloud('minValueToDisplay');
      }
   }

   rtl(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxTagCloud('rtl', arg);
      } else {
          return this.host.jqxTagCloud('rtl');
      }
   }

   sortBy(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('sortBy', arg);
      } else {
          return this.host.jqxTagCloud('sortBy');
      }
   }

   sortOrder(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('sortOrder', arg);
      } else {
          return this.host.jqxTagCloud('sortOrder');
      }
   }

   source(arg?: jqwidgets.TagCloudSource): jqwidgets.TagCloudSource {
      if (arg !== undefined) {
          this.host.jqxTagCloud('source', arg);
      } else {
          return this.host.jqxTagCloud('source');
      }
   }

   tagRenderer(arg?: (itemData: jqwidgets.TagCloudTagRenderer['itemData'], minValue: jqwidgets.TagCloudTagRenderer['minValue'], valueRange: jqwidgets.TagCloudTagRenderer['valueRange']) => any): (itemData: jqwidgets.TagCloudTagRenderer['itemData'], minValue: jqwidgets.TagCloudTagRenderer['minValue'], valueRange: jqwidgets.TagCloudTagRenderer['valueRange']) => any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('tagRenderer', arg);
      } else {
          return this.host.jqxTagCloud('tagRenderer');
      }
   }

   takeTopWeightedItems(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxTagCloud('takeTopWeightedItems', arg);
      } else {
          return this.host.jqxTagCloud('takeTopWeightedItems');
      }
   }

   textColor(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('textColor', arg);
      } else {
          return this.host.jqxTagCloud('textColor');
      }
   }

   urlBase(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('urlBase', arg);
      } else {
          return this.host.jqxTagCloud('urlBase');
      }
   }

   urlMember(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('urlMember', arg);
      } else {
          return this.host.jqxTagCloud('urlMember');
      }
   }

   valueMember(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxTagCloud('valueMember', arg);
      } else {
          return this.host.jqxTagCloud('valueMember');
      }
   }

   width(arg?: string | number): string | number {
      if (arg !== undefined) {
          this.host.jqxTagCloud('width', arg);
      } else {
          return this.host.jqxTagCloud('width');
      }
   }


   // jqxTagCloudComponent functions
   destroy(): void {
      this.host.jqxTagCloud('destroy');
   }

   findTagIndex(tag: string): number {
      return this.host.jqxTagCloud('findTagIndex', tag);
   }

   getHiddenTagsList(): Array<any> {
      return this.host.jqxTagCloud('getHiddenTagsList');
   }

   getRenderedTags(): Array<any> {
      return this.host.jqxTagCloud('getRenderedTags');
   }

   getTagsList(): Array<any> {
      return this.host.jqxTagCloud('getTagsList');
   }

   hideItem(index: number): void {
      this.host.jqxTagCloud('hideItem', index);
   }

   insertAt(index: number, item: any): void {
      this.host.jqxTagCloud('insertAt', index, item);
   }

   removeAt(index: number): void {
      this.host.jqxTagCloud('removeAt', index);
   }

   updateAt(index: number, item: any): void {
      this.host.jqxTagCloud('updateAt', index, item);
   }

   showItem(index: number): void {
      this.host.jqxTagCloud('showItem', index);
   }


   // jqxTagCloudComponent events
   @Output() onBindingComplete = new EventEmitter();
   @Output() onItemClick = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('itemClick', (eventData: any) => { this.onItemClick.emit(eventData); });
   }

} //jqxTagCloudComponent

// ajax/libs/jqwidgets/13.2.0/jqwidgets-vue/vue_jqxtagcloud.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxdata.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxtagcloud.js';

    export default {
        props: {
            alterTextCase: String,
            disabled: Boolean,
            displayLimit: Number,
            displayMember: String,
            displayValue: Boolean,
            fontSizeUnit: String,
            height: [Number, String],
            maxColor: String,
            maxFontSize: Number,
            maxValueToDisplay: Number,
            minColor: String,
            minFontSize: Number,
            minValueToDisplay: Number,
            rtl: Boolean,
            sortBy: String,
            sortOrder: String,
            source: Object,
            tagRenderer: Function,
            takeTopWeightedItems: Boolean,
            textColor: String,
            urlBase: String,
            urlMember: String,
            valueMember: String,
            width: [Number, String],
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxTagCloud' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxTagCloud(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxTagCloud(usedProps[i]);
                }
                return resultToReturn;
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxTagCloud('destroy');  
            },
            findTagIndex: function(tag) {
                return JQXLite(this.componentSelector).jqxTagCloud('findTagIndex', tag);  
            },
            getHiddenTagsList: function() {
                return JQXLite(this.componentSelector).jqxTagCloud('getHiddenTagsList');  
            },
            getRenderedTags: function() {
                return JQXLite(this.componentSelector).jqxTagCloud('getRenderedTags');  
            },
            getTagsList: function() {
                return JQXLite(this.componentSelector).jqxTagCloud('getTagsList');  
            },
            hideItem: function(index) {
                JQXLite(this.componentSelector).jqxTagCloud('hideItem', index);  
            },
            insertAt: function(index, item) {
                JQXLite(this.componentSelector).jqxTagCloud('insertAt', index, item);  
            },
            removeAt: function(index) {
                JQXLite(this.componentSelector).jqxTagCloud('removeAt', index);  
            },
            updateAt: function(index, item) {
                JQXLite(this.componentSelector).jqxTagCloud('updateAt', index, item);  
            },
            showItem: function(index) {
                JQXLite(this.componentSelector).jqxTagCloud('showItem', index);  
            },
            _alterTextCase: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('alterTextCase', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('alterTextCase');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('disabled');
                }
            },
            _displayLimit: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('displayLimit', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('displayLimit');
                }
            },
            _displayMember: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('displayMember', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('displayMember');
                }
            },
            _displayValue: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('displayValue', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('displayValue');
                }
            },
            _fontSizeUnit: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('fontSizeUnit', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('fontSizeUnit');
                }
            },
            _height: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('height', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('height');
                }
            },
            _maxColor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('maxColor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('maxColor');
                }
            },
            _maxFontSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('maxFontSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('maxFontSize');
                }
            },
            _maxValueToDisplay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('maxValueToDisplay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('maxValueToDisplay');
                }
            },
            _minColor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('minColor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('minColor');
                }
            },
            _minFontSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('minFontSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('minFontSize');
                }
            },
            _minValueToDisplay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('minValueToDisplay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('minValueToDisplay');
                }
            },
            _rtl: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('rtl', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('rtl');
                }
            },
            _sortBy: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('sortBy', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('sortBy');
                }
            },
            _sortOrder: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('sortOrder', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('sortOrder');
                }
            },
            _source: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('source', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('source');
                }
            },
            _tagRenderer: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('tagRenderer', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('tagRenderer');
                }
            },
            _takeTopWeightedItems: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('takeTopWeightedItems', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('takeTopWeightedItems');
                }
            },
            _textColor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('textColor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('textColor');
                }
            },
            _urlBase: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('urlBase', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('urlBase');
                }
            },
            _urlMember: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('urlMember', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('urlMember');
                }
            },
            _valueMember: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('valueMember', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('valueMember');
                }
            },
            _width: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxTagCloud('width', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxTagCloud('width');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxTagCloud(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['alterTextCase','disabled','displayLimit','displayMember','displayValue','fontSizeUnit','height','maxColor','maxFontSize','maxValueToDisplay','minColor','minFontSize','minValueToDisplay','rtl','sortBy','sortOrder','source','tagRenderer','takeTopWeightedItems','textColor','urlBase','urlMember','valueMember','width'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'alterTextCase', {
                    get: function() {
                        return that._alterTextCase();
                    },
                    set: function(newValue) {
                        that._alterTextCase(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get: function() {
                        return that._disabled();
                    },
                    set: function(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'displayLimit', {
                    get: function() {
                        return that._displayLimit();
                    },
                    set: function(newValue) {
                        that._displayLimit(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'displayMember', {
                    get: function() {
                        return that._displayMember();
                    },
                    set: function(newValue) {
                        that._displayMember(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'displayValue', {
                    get: function() {
                        return that._displayValue();
                    },
                    set: function(newValue) {
                        that._displayValue(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'fontSizeUnit', {
                    get: function() {
                        return that._fontSizeUnit();
                    },
                    set: function(newValue) {
                        that._fontSizeUnit(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'height', {
                    get: function() {
                        return that._height();
                    },
                    set: function(newValue) {
                        that._height(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'maxColor', {
                    get: function() {
                        return that._maxColor();
                    },
                    set: function(newValue) {
                        that._maxColor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'maxFontSize', {
                    get: function() {
                        return that._maxFontSize();
                    },
                    set: function(newValue) {
                        that._maxFontSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'maxValueToDisplay', {
                    get: function() {
                        return that._maxValueToDisplay();
                    },
                    set: function(newValue) {
                        that._maxValueToDisplay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minColor', {
                    get: function() {
                        return that._minColor();
                    },
                    set: function(newValue) {
                        that._minColor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minFontSize', {
                    get: function() {
                        return that._minFontSize();
                    },
                    set: function(newValue) {
                        that._minFontSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'minValueToDisplay', {
                    get: function() {
                        return that._minValueToDisplay();
                    },
                    set: function(newValue) {
                        that._minValueToDisplay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'rtl', {
                    get: function() {
                        return that._rtl();
                    },
                    set: function(newValue) {
                        that._rtl(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'sortBy', {
                    get: function() {
                        return that._sortBy();
                    },
                    set: function(newValue) {
                        that._sortBy(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'sortOrder', {
                    get: function() {
                        return that._sortOrder();
                    },
                    set: function(newValue) {
                        that._sortOrder(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'source', {
                    get: function() {
                        return that._source();
                    },
                    set: function(newValue) {
                        that._source(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tagRenderer', {
                    get: function() {
                        return that._tagRenderer();
                    },
                    set: function(newValue) {
                        that._tagRenderer(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'takeTopWeightedItems', {
                    get: function() {
                        return that._takeTopWeightedItems();
                    },
                    set: function(newValue) {
                        that._takeTopWeightedItems(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'textColor', {
                    get: function() {
                        return that._textColor();
                    },
                    set: function(newValue) {
                        that._textColor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'urlBase', {
                    get: function() {
                        return that._urlBase();
                    },
                    set: function(newValue) {
                        that._urlBase(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'urlMember', {
                    get: function() {
                        return that._urlMember();
                    },
                    set: function(newValue) {
                        that._urlMember(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'valueMember', {
                    get: function() {
                        return that._valueMember();
                    },
                    set: function(newValue) {
                        that._valueMember(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'width', {
                    get: function() {
                        return that._width();
                    },
                    set: function(newValue) {
                        that._width(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('bindingComplete', function (event) { that.$emit('bindingComplete', event); });
                JQXLite(this.componentSelector).on('itemClick', function (event) { that.$emit('itemClick', event); });
            }
        }
    }
</script>
