// ajax/libs/jqwidgets/13.0.0/jqwidgets-vue/vue_jqxsortable.vue
<template>
    <div v-bind:id="id">
        <slot></slot>
    </div>
</template>

<script>
    import '../jqwidgets/jqxcore.js';
    import '../jqwidgets/jqxbuttons.js';
    import '../jqwidgets/jqxsortable.js';

    export default {
        props: {
            appendTo: String,
            axis: String,
            cancel: String,
            connectWith: String,
            containment: String,
            cursor: String,
            cursorAt: Object,
            delay: Number,
            disabled: Boolean,
            distance: Number,
            dropOnEmpty: Boolean,
            forceHelperSize: Boolean,
            forcePlaceholderSize: Boolean,
            grid: Array,
            handle: String,
            helper: String,
            items: String,
            opacity: Number,
            placeholderShow: String,
            revert: Boolean,
            scroll: Boolean,
            scrollSensitivity: Number,
            scrollSpeed: Number,
            tolerance: String,
            zIndex: Number,
            autoCreate: {
                default: true,
                type: Boolean
            }
        },
        created: function () {
            this.id = 'jqxSortable' + JQXLite.generateID();
            this.componentSelector = '#' + this.id;
        },
        mounted: function () {
            if (this.autoCreate) this.__createComponent__();
        },
        methods: {
            createComponent: function (options) {
                if (!this.autoCreate) this.__createComponent__(options)
                else console.warn('Component is already created! If you want to use createComponent, please set "autoCreate" property to "false".');
            },
            setOptions: function (options) {
                JQXLite(this.componentSelector).jqxSortable(options);
            },
            getOptions: function () {
                const usedProps = Object.keys(this.__manageProps__());
                const resultToReturn = {};
                for (let i = 0; i < usedProps.length; i++) {
                    resultToReturn[usedProps[i]] = JQXLite(this.componentSelector).jqxSortable(usedProps[i]);
                }
                return resultToReturn;
            },
            cancelMethod: function() {
                JQXLite(this.componentSelector).jqxSortable('cancelMethod');  
            },
            destroy: function() {
                JQXLite(this.componentSelector).jqxSortable('destroy');  
            },
            disable: function() {
                JQXLite(this.componentSelector).jqxSortable('disable');  
            },
            enable: function() {
                JQXLite(this.componentSelector).jqxSortable('enable');  
            },
            refresh: function() {
                JQXLite(this.componentSelector).jqxSortable('refresh');  
            },
            refreshPositions: function() {
                JQXLite(this.componentSelector).jqxSortable('refreshPositions');  
            },
            serialize: function(object) {
                return JQXLite(this.componentSelector).jqxSortable('serialize', object);  
            },
            toArray: function() {
                return JQXLite(this.componentSelector).jqxSortable('toArray');  
            },
            _appendTo: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('appendTo', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('appendTo');
                }
            },
            _axis: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('axis', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('axis');
                }
            },
            _cancel: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cancel', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cancel');
                }
            },
            _connectWith: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('connectWith', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('connectWith');
                }
            },
            _containment: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('containment', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('containment');
                }
            },
            _cursor: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cursor', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cursor');
                }
            },
            _cursorAt: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('cursorAt', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('cursorAt');
                }
            },
            _delay: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('delay', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('delay');
                }
            },
            _disabled: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('disabled', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('disabled');
                }
            },
            _distance: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('distance', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('distance');
                }
            },
            _dropOnEmpty: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('dropOnEmpty', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('dropOnEmpty');
                }
            },
            _forceHelperSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('forceHelperSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('forceHelperSize');
                }
            },
            _forcePlaceholderSize: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('forcePlaceholderSize');
                }
            },
            _grid: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('grid', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('grid');
                }
            },
            _handle: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('handle', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('handle');
                }
            },
            _helper: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('helper', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('helper');
                }
            },
            _items: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('items', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('items');
                }
            },
            _opacity: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('opacity', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('opacity');
                }
            },
            _placeholderShow: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('placeholderShow', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('placeholderShow');
                }
            },
            _revert: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('revert', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('revert');
                }
            },
            _scroll: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scroll', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scroll');
                }
            },
            _scrollSensitivity: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scrollSensitivity', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scrollSensitivity');
                }
            },
            _scrollSpeed: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('scrollSpeed', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('scrollSpeed');
                }
            },
            _tolerance: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('tolerance', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('tolerance');
                }
            },
            _zIndex: function(arg) {
                if (arg !== undefined) {
                    JQXLite(this.componentSelector).jqxSortable('zIndex', arg)
                } else {
                    return JQXLite(this.componentSelector).jqxSortable('zIndex');
                }
            },
            __createComponent__: function (options) {
                let widgetOptions;
                options ? widgetOptions = options : widgetOptions = this.__manageProps__();
                JQXLite(this.componentSelector).jqxSortable(widgetOptions);
                this.__extendProps__();
                this.__wireEvents__();
            },
            __manageProps__: function () {
                const widgetProps = ['appendTo','axis','cancel','connectWith','containment','cursor','cursorAt','delay','disabled','distance','dropOnEmpty','forceHelperSize','forcePlaceholderSize','grid','handle','helper','items','opacity','placeholderShow','revert','scroll','scrollSensitivity','scrollSpeed','tolerance','zIndex'];
                const componentProps = this.$options.propsData;
                let options = {};

                for (let prop in componentProps) {
                    if (widgetProps.indexOf(prop) !== -1) {
                        options[prop] = componentProps[prop];
                    }
                }
                return options;
            },
            __extendProps__: function () {
                const that = this;

                Object.defineProperty(that, 'appendTo', {
                    get: function() {
                        return that._appendTo();
                    },
                    set: function(newValue) {
                        that._appendTo(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'axis', {
                    get: function() {
                        return that._axis();
                    },
                    set: function(newValue) {
                        that._axis(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cancel', {
                    get: function() {
                        return that._cancel();
                    },
                    set: function(newValue) {
                        that._cancel(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'connectWith', {
                    get: function() {
                        return that._connectWith();
                    },
                    set: function(newValue) {
                        that._connectWith(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'containment', {
                    get: function() {
                        return that._containment();
                    },
                    set: function(newValue) {
                        that._containment(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cursor', {
                    get: function() {
                        return that._cursor();
                    },
                    set: function(newValue) {
                        that._cursor(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'cursorAt', {
                    get: function() {
                        return that._cursorAt();
                    },
                    set: function(newValue) {
                        that._cursorAt(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'delay', {
                    get: function() {
                        return that._delay();
                    },
                    set: function(newValue) {
                        that._delay(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'disabled', {
                    get: function() {
                        return that._disabled();
                    },
                    set: function(newValue) {
                        that._disabled(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'distance', {
                    get: function() {
                        return that._distance();
                    },
                    set: function(newValue) {
                        that._distance(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'dropOnEmpty', {
                    get: function() {
                        return that._dropOnEmpty();
                    },
                    set: function(newValue) {
                        that._dropOnEmpty(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'forceHelperSize', {
                    get: function() {
                        return that._forceHelperSize();
                    },
                    set: function(newValue) {
                        that._forceHelperSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'forcePlaceholderSize', {
                    get: function() {
                        return that._forcePlaceholderSize();
                    },
                    set: function(newValue) {
                        that._forcePlaceholderSize(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'grid', {
                    get: function() {
                        return that._grid();
                    },
                    set: function(newValue) {
                        that._grid(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'handle', {
                    get: function() {
                        return that._handle();
                    },
                    set: function(newValue) {
                        that._handle(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'helper', {
                    get: function() {
                        return that._helper();
                    },
                    set: function(newValue) {
                        that._helper(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'items', {
                    get: function() {
                        return that._items();
                    },
                    set: function(newValue) {
                        that._items(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'opacity', {
                    get: function() {
                        return that._opacity();
                    },
                    set: function(newValue) {
                        that._opacity(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'placeholderShow', {
                    get: function() {
                        return that._placeholderShow();
                    },
                    set: function(newValue) {
                        that._placeholderShow(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'revert', {
                    get: function() {
                        return that._revert();
                    },
                    set: function(newValue) {
                        that._revert(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scroll', {
                    get: function() {
                        return that._scroll();
                    },
                    set: function(newValue) {
                        that._scroll(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scrollSensitivity', {
                    get: function() {
                        return that._scrollSensitivity();
                    },
                    set: function(newValue) {
                        that._scrollSensitivity(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'scrollSpeed', {
                    get: function() {
                        return that._scrollSpeed();
                    },
                    set: function(newValue) {
                        that._scrollSpeed(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'tolerance', {
                    get: function() {
                        return that._tolerance();
                    },
                    set: function(newValue) {
                        that._tolerance(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
                Object.defineProperty(that, 'zIndex', {
                    get: function() {
                        return that._zIndex();
                    },
                    set: function(newValue) {
                        that._zIndex(newValue);
                    },
                    enumerable: true,
                    configurable: true
                });
            },
            __wireEvents__: function () {
                const that = this;

                JQXLite(this.componentSelector).on('activate', function (event) { that.$emit('activate', event); });
                JQXLite(this.componentSelector).on('beforeStop', function (event) { that.$emit('beforeStop', event); });
                JQXLite(this.componentSelector).on('change', function (event) { that.$emit('change', event); });
                JQXLite(this.componentSelector).on('deactivate', function (event) { that.$emit('deactivate', event); });
                JQXLite(this.componentSelector).on('out', function (event) { that.$emit('out', event); });
                JQXLite(this.componentSelector).on('over', function (event) { that.$emit('over', event); });
                JQXLite(this.componentSelector).on('receive', function (event) { that.$emit('receive', event); });
                JQXLite(this.componentSelector).on('remove', function (event) { that.$emit('remove', event); });
                JQXLite(this.componentSelector).on('sort', function (event) { that.$emit('sort', event); });
                JQXLite(this.componentSelector).on('start', function (event) { that.$emit('start', event); });
                JQXLite(this.componentSelector).on('stop', function (event) { that.$emit('stop', event); });
                JQXLite(this.componentSelector).on('update', function (event) { that.$emit('update', event); });
            }
        }
    }
</script>

// ajax/libs/jqwidgets/12.0.2/jqwidgets-ts/angular_jqxsortable.ts
/*
jQWidgets v12.0.0 (2021-Feb)
Copyright (c) 2011-2021 jQWidgets.
License: https://jqwidgets.com/license/
*/
/* eslint-disable */

/// <reference path="jqwidgets.d.ts" />

import '../jqwidgets/jqxcore.js';
import '../jqwidgets/jqxbuttons.js';
import '../jqwidgets/jqxsortable.js';

import { Component, Input, Output, EventEmitter, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
declare let JQXLite: any;

@Component({
    selector: 'jqxSortable',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxSortableComponent implements OnChanges
{
   @Input('appendTo') attrAppendTo: string;
   @Input('axis') attrAxis: number | string;
   @Input('cancel') attrCancel: string;
   @Input('connectWith') attrConnectWith: string | boolean;
   @Input('containment') attrContainment: string | boolean;
   @Input('cursor') attrCursor: string;
   @Input('cursorAt') attrCursorAt: jqwidgets.SortableCursorAt;
   @Input('delay') attrDelay: number;
   @Input('disabled') attrDisabled: boolean;
   @Input('distance') attrDistance: number;
   @Input('dropOnEmpty') attrDropOnEmpty: boolean;
   @Input('forceHelperSize') attrForceHelperSize: boolean;
   @Input('forcePlaceholderSize') attrForcePlaceholderSize: boolean;
   @Input('grid') attrGrid: Array<number>;
   @Input('handle') attrHandle: string | boolean;
   @Input('helper') attrHelper: (originalEvent?: any, content?: any) => void | 'original' | 'clone';
   @Input('items') attrItems: string;
   @Input('opacity') attrOpacity: number | boolean;
   @Input('placeholderShow') attrPlaceholderShow: string | boolean;
   @Input('revert') attrRevert: number | boolean;
   @Input('scroll') attrScroll: boolean;
   @Input('scrollSensitivity') attrScrollSensitivity: number;
   @Input('scrollSpeed') attrScrollSpeed: number;
   @Input('tolerance') attrTolerance: string;
   @Input('zIndex') attrZIndex: number;
   @Input('width') attrWidth: string | number;
   @Input('height') attrHeight: string | number;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['appendTo','axis','cancel','connectWith','containment','cursor','cursorAt','delay','disabled','distance','dropOnEmpty','forceHelperSize','forcePlaceholderSize','grid','handle','helper','items','opacity','placeholderShow','revert','scroll','scrollSensitivity','scrollSpeed','tolerance','zIndex'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxSortable;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean = false;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxSortable(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxSortable(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxSortable(this.properties[i])) {
                  this.host.jqxSortable(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if ((attrValue && !hostValue) || (!attrValue && hostValue)) {
         return false;
      }
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      if (classes.length > 0) {
        childEl.classList.add(...classes);
      }
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (this.host) {
         return;
      }
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxSortable', options);

   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      if(this.host) this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxSortable('setOptions', options);
   }

   // jqxSortableComponent properties
   appendTo(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxSortable('appendTo', arg);
      } else {
          return this.host.jqxSortable('appendTo');
      }
   }

   axis(arg?: number | string): number | string {
      if (arg !== undefined) {
          this.host.jqxSortable('axis', arg);
      } else {
          return this.host.jqxSortable('axis');
      }
   }

   cancel(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxSortable('cancel', arg);
      } else {
          return this.host.jqxSortable('cancel');
      }
   }

   connectWith(arg?: string | boolean): string | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('connectWith', arg);
      } else {
          return this.host.jqxSortable('connectWith');
      }
   }

   containment(arg?: string | boolean): string | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('containment', arg);
      } else {
          return this.host.jqxSortable('containment');
      }
   }

   cursor(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxSortable('cursor', arg);
      } else {
          return this.host.jqxSortable('cursor');
      }
   }

   cursorAt(arg?: jqwidgets.SortableCursorAt): jqwidgets.SortableCursorAt {
      if (arg !== undefined) {
          this.host.jqxSortable('cursorAt', arg);
      } else {
          return this.host.jqxSortable('cursorAt');
      }
   }

   delay(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxSortable('delay', arg);
      } else {
          return this.host.jqxSortable('delay');
      }
   }

   disabled(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('disabled', arg);
      } else {
          return this.host.jqxSortable('disabled');
      }
   }

   distance(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxSortable('distance', arg);
      } else {
          return this.host.jqxSortable('distance');
      }
   }

   dropOnEmpty(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('dropOnEmpty', arg);
      } else {
          return this.host.jqxSortable('dropOnEmpty');
      }
   }

   forceHelperSize(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('forceHelperSize', arg);
      } else {
          return this.host.jqxSortable('forceHelperSize');
      }
   }

   forcePlaceholderSize(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('forcePlaceholderSize', arg);
      } else {
          return this.host.jqxSortable('forcePlaceholderSize');
      }
   }

   grid(arg?: Array<number>): Array<number> {
      if (arg !== undefined) {
          this.host.jqxSortable('grid', arg);
      } else {
          return this.host.jqxSortable('grid');
      }
   }

   handle(arg?: string | boolean): string | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('handle', arg);
      } else {
          return this.host.jqxSortable('handle');
      }
   }

   helper(arg?: (originalEvent?: any, content?: any) => void | 'original' | 'clone'): (originalEvent?: any, content?: any) => void | 'original' | 'clone' {
      if (arg !== undefined) {
          this.host.jqxSortable('helper', arg);
      } else {
          return this.host.jqxSortable('helper');
      }
   }

   items(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxSortable('items', arg);
      } else {
          return this.host.jqxSortable('items');
      }
   }

   opacity(arg?: number | boolean): number | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('opacity', arg);
      } else {
          return this.host.jqxSortable('opacity');
      }
   }

   placeholderShow(arg?: string | boolean): string | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('placeholderShow', arg);
      } else {
          return this.host.jqxSortable('placeholderShow');
      }
   }

   revert(arg?: number | boolean): number | boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('revert', arg);
      } else {
          return this.host.jqxSortable('revert');
      }
   }

   scroll(arg?: boolean): boolean {
      if (arg !== undefined) {
          this.host.jqxSortable('scroll', arg);
      } else {
          return this.host.jqxSortable('scroll');
      }
   }

   scrollSensitivity(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxSortable('scrollSensitivity', arg);
      } else {
          return this.host.jqxSortable('scrollSensitivity');
      }
   }

   scrollSpeed(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxSortable('scrollSpeed', arg);
      } else {
          return this.host.jqxSortable('scrollSpeed');
      }
   }

   tolerance(arg?: string): string {
      if (arg !== undefined) {
          this.host.jqxSortable('tolerance', arg);
      } else {
          return this.host.jqxSortable('tolerance');
      }
   }

   zIndex(arg?: number): number {
      if (arg !== undefined) {
          this.host.jqxSortable('zIndex', arg);
      } else {
          return this.host.jqxSortable('zIndex');
      }
   }


   // jqxSortableComponent functions
   cancelMethod(): void {
      this.host.jqxSortable('cancelMethod');
   }

   destroy(): void {
      this.host.jqxSortable('destroy');
   }

   disable(): void {
      this.host.jqxSortable('disable');
   }

   enable(): void {
      this.host.jqxSortable('enable');
   }

   refresh(): void {
      this.host.jqxSortable('refresh');
   }

   refreshPositions(): void {
      this.host.jqxSortable('refreshPositions');
   }

   serialize(object: undefined): string {
      return this.host.jqxSortable('serialize', object);
   }

   toArray(): Array<any> {
      return this.host.jqxSortable('toArray');
   }


   // jqxSortableComponent events
   @Output() onActivate = new EventEmitter();
   @Output() onBeforeStop = new EventEmitter();
   @Output() onChange = new EventEmitter();
   @Output() onDeactivate = new EventEmitter();
   @Output() onOut = new EventEmitter();
   @Output() onOver = new EventEmitter();
   @Output() onReceive = new EventEmitter();
   @Output() onRemove = new EventEmitter();
   @Output() onSort = new EventEmitter();
   @Output() onStart = new EventEmitter();
   @Output() onStop = new EventEmitter();
   @Output() onUpdate = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('activate', (eventData: any) => { this.onActivate.emit(eventData); });
      this.host.on('beforeStop', (eventData: any) => { this.onBeforeStop.emit(eventData); });
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); });
      this.host.on('deactivate', (eventData: any) => { this.onDeactivate.emit(eventData); });
      this.host.on('out', (eventData: any) => { this.onOut.emit(eventData); });
      this.host.on('over', (eventData: any) => { this.onOver.emit(eventData); });
      this.host.on('receive', (eventData: any) => { this.onReceive.emit(eventData); });
      this.host.on('remove', (eventData: any) => { this.onRemove.emit(eventData); });
      this.host.on('sort', (eventData: any) => { this.onSort.emit(eventData); });
      this.host.on('start', (eventData: any) => { this.onStart.emit(eventData); });
      this.host.on('stop', (eventData: any) => { this.onStop.emit(eventData); });
      this.host.on('update', (eventData: any) => { this.onUpdate.emit(eventData); });
   }

} //jqxSortableComponent
